import { Roboto, Miniver } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
   weight: "400",
   subsets: ["latin"]
});
const MiniverFont = Miniver({
   subsets: ["latin"],
   display: "swap",
   variable: "--miniver-font",
   weight: "400",
})

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app"
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={`${roboto.className}  ${MiniverFont.variable}`}>
            {children}
         </body>
      </html>
   );
}
